### ISSUE TITLE
Update App Engine oauth decorators to work with Google+ web server flow

### ISSUE THREAD

**Issue by espeed** [googleapis/oauth2client#61]
The appengine decorators use the User's service get_current_user() method to determine if a user is logged in; however, there is no easy way to adapt the decorator to use the Google+ web server flow for authentication. 

See https://developers.google.com/+/web/signin/server-side-flow

Adding a get_current_user method to the decorator would make it easier to override and adapt.

**Comment by theacodes** [comment]
Hi, this project is deprecated. Please move to google-auth.
